create table if not exists public.machine_states (
  machine_id text primary key,
  display_name text not null default '',
  locked boolean not null default false,
  reset_serial integer not null default 0,
  current_session_id text not null default '',
  current_player_name text not null default '',
  last_snapshot jsonb,
  last_ended_session jsonb,
  updated_at_ms bigint not null default 0,
  assigned_setting integer not null default 1,
  updated_at timestamptz not null default now()
);

create table if not exists public.issued_passwords (
  password text primary key,
  machine_id text not null,
  player_name text not null default '',
  status text not null default 'issued',
  issued_at_ms bigint not null default 0,
  used_at_ms bigint not null default 0,
  session_id text not null default ''
);

create table if not exists public.sessions (
  session_id text primary key,
  token text not null default '',
  password text not null default '',
  machine_id text not null,
  player_name text not null default '',
  status text not null default 'active',
  started_at_ms bigint not null default 0,
  ended_at_ms bigint not null default 0,
  reset_serial_at_start integer not null default 0,
  start_snapshot jsonb,
  result_record jsonb,
  sheets jsonb
);

create table if not exists public.machine_commands (
  id bigint generated by default as identity primary key,
  machine_id text not null,
  command jsonb not null,
  created_at_ms bigint not null default 0,
  created_at timestamptz not null default now()
);

create table if not exists public.session_results (
  id bigint generated by default as identity primary key,
  ended_at_ms bigint not null default 0,
  machine_id text not null default '',
  record jsonb not null,
  created_at timestamptz not null default now()
);

create index if not exists machine_commands_poll_idx on public.machine_commands(machine_id, id);
create index if not exists session_results_ended_idx on public.session_results(ended_at_ms desc);
create index if not exists issued_passwords_issued_idx on public.issued_passwords(issued_at_ms desc);


alter table public.sessions add column if not exists start_snapshot jsonb;
